language: php

php:
  - 5.5
  - 5.6

before_script:
  - cd ..
  - git clone git://github.com/uthando-cms/uthando.git
  - cd uthando
  - composer install --no-dev
  - composer require --update-no-dev codeclimate/php-test-reporter
  - cp -R ../uthando-admin ./module/UthandoAdmin
  - cd module/UthandoAdmin/test

script:
  - phpunit

after_script:
  - cd ../../../
  - php vendor/bin/test-reporter --coverage-report=build/logs/clover-UthandoAdmin.xml
