language: php

php:
  - 5.5
  - 5.6

before_script:
  - cd ..
  - git clone git://github.com/uthando-cms/uthando.git
  - cd uthando
  - composer install
  - composer require phpunit/phpunit:~4.0
  - composer require uthando-cms/uthando-common
  - composer require uthando-cms/uthando-navigation
  - composer require uthando-cms/uthando-theme-manager
  - composer require uthando-cms/uthando-user
  - composer require rwoverdijk/assetmanager
  - cp -R ../uthando-admin ./module/UthandoAdmin
  - cd module/UthandoAdmin/test

script:
  - phpunit

after_script:
  - cd ../../../
  - php vendor/bin/test-reporter --coverage-report=build/logs/clover-UthandoAdmin.xml
