<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UthandoAdmin\Controller\IndexController'             => __DIR__ . '/src/UthandoAdmin/Controller/IndexController.php',
    'UthandoAdmin\View\PhpInfo'                           => __DIR__ . '/src/UthandoAdmin/View/PhpInfo.php',
    'UthandoAdmin\View\UthandoFormElement'                => __DIR__ . '/src/UthandoAdmin/View/UthandoFormElement.php',
    'UthandoAdmin\View\DatePicker'                        => __DIR__ . '/src/UthandoAdmin/View/DatePicker.php',
    'UthandoAdmin\View\TextEditor'                        => __DIR__ . '/src/UthandoAdmin/View/TextEditor.php',
    'UthandoAdmin\Service\AdminNavigationFactory'         => __DIR__ . '/src/UthandoAdmin/Service/AdminNavigationFactory.php',
    'UthandoAdmin\AdminException'                         => __DIR__ . '/src/UthandoAdmin/AdminException.php',
    'UthandoAdmin\Module'                                 => __DIR__ . '/Module.php',
    'UthandoAdminTest\Bootstrap'                          => __DIR__ . '/test/Bootstrap.php',
    'UthandoAdminTest\Controller\IndexControllerTest'     => __DIR__ . '/test/UthandoAdminTest/Controller/IndexControllerTest.php',
    'UthandoAdminTest\View\PhpInfoTest'                   => __DIR__ . '/test/UthandoAdminTest/View/PhpInfo.php',
    'UthandoAdminTest\View\UthandoFormElementTest'        => __DIR__ . '/test/UthandoAdminTest/View/UthandoFormElementTest.php',
    'UthandoAdminTest\Service\AdminNavigationFactoryTest' => __DIR__ . '/test/UthandoAdminTest/Service/AdminNavigationFactoryTest.php',
    'UthandoAdminTest\Framework\TestCase'                 => __DIR__ . '/test/UthandoAdminTest/Framework/TestCase.php',
    'UthandoAdminTest\Framework\TestForm'                 => __DIR__ . '/test/UthandoAdminTest/Framework/TestForm.php',
);
