<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UthandoAdmin\Controller\IndexController'             => __DIR__ . '/src/UthandoAdmin/Controller/IndexController.php',
    'UthandoAdmin\View\PhpInfo'                           => __DIR__ . '/src/UthandoAdmin/View/PhpInfo.php',
    'UthandoAdmin\View\UthandoFormElement'                => __DIR__ . '/src/UthandoAdmin/View/UthandoFormElement.php',
    'UthandoAdmin\View\TextEditor'                        => __DIR__ . '/src/UthandoAdmin/View/TextEditor.php',
    'UthandoAdmin\Service\AdminNavigationFactory'         => __DIR__ . '/src/UthandoAdmin/Service/AdminNavigationFactory.php',
    'UthandoAdmin\AdminException'                         => __DIR__ . '/src/UthandoAdmin/AdminException.php',
    'UthandoAdmin\Module'                                 => __DIR__ . '/Module.php',
);
