<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'uthando-admin/index/index'             => __DIR__ . '/view/uthando-admin/index/index.phtml',
    'uthando-admin/partial/add-edit-form'   => __DIR__ . '/view/uthando-admin/partial/add-edit-form.phtml',
    'uthando-admin/partial/edit-actions'    => __DIR__ . '/view/uthando-admin/partial/edit-actions.phtml',
    'uthando-admin/partial/form-element'    => __DIR__ . '/view/uthando-admin/partial/form-element.phtml',
    'uthando-admin/partial/search'          => __DIR__ . '/view/uthando-admin/partial/search.phtml',
    'uthando-admin/partial/tb-form-element' => __DIR__ . '/view/uthando-admin/partial/tb-form-element.phtml',
);
