<?php
$routeParams = (is_array($this->routeParams)) ? $this->routeParams : [];
$form = $this->form;
$routeArray = ['action' => $this->formAction];
if (isset($this->primaryKey)) $routeArray['id'] = $this->primaryKey;
?>
<div class="row">
	<form class="col-sm-12 form-horizontal" method="post" action="<?=$this->url($this->postRoute, array_merge($routeParams, $routeArray)) ?>">
		<fieldset>
			<legend><?=ucwords($this->formAction); ?> <?=$this->formName;?> Form:</legend>
			<?=$this->uthandoFormElement();?>
			<input type="hidden" name="action" value="<?=$this->formAction;?>">
			
			<div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary" data-loading-text="Please wait...">
                    	Submit
                    </button>
                    <button type="button" class="btn btn-warning"  data-loading-text="Please wait..." onClick="window.location = '<?=$this->url($this->cancelRoute, array_merge($routeParams, $routeArray));?>';">
                    	Cancel
                    </button>
                </div>
            </div>
		</fieldset>
	</form>
</div>

