
<?php $routeParams = (is_array($this->routeParams)) ? $this->routeParams : array(); ?>

<a href="<?=$this->url($this->route, array(
	'id' => $this->id
)); ?>" class="btn">Edit</a>
&nbsp;

<!-- Button to trigger modal -->
<a href="#<?=$this->tableName;?>Model<?=$this->id;?>" class="btn btn-danger" data-toggle="modal">Delete</a>
<!-- Modal -->
<div class="modal hide fade" id="<?=$this->tableName;?>Model<?=$this->id;?>">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h3 id="<?=$this->tableName;?>Model<?=$this->id;?>Label">Warning</h3>
  </div>
  <form class="form-horizontal"  method="post" action="<?=$this->url($this->route, array(
        'action' => 'delete',
    )) ?>">
        <div class="modal-body">
            <p>Are you sure you want to delete this <?=$this->tableName;?>.</p>
            <p class="label label-important">This action cannot be undone</p>
        </div>
        <input type="hidden" name="<?=$this->pk;?>" value="<?=$this->id;?>">
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">No Don't Do It</button>
            <button type="submit" name="submit" class="btn btn-danger" value="delete">Yes Delete It</button>
        </div>
    </form>
</div>