<?php $this->bootstrap()->enable();?>
<?=$this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <?=$this->headTitle('Control Panel')->setSeparator(' - ')->setAutoEscape(false);?>

        <?=$this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('rating', 'general');?> 
        
        <!-- Styles -->
        <?=$this->headLink()
            ->appendStylesheet($this->basePath('css/uthando-admin.css'));?>

        <!-- Scripts -->
        <?=$this->headScript();?>

    </head>
    <body>
    	<nav class="navbar navbar-default navbar-fixed-top">
    		<div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".admin-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?=$this->url('home'); ?>">
                        Uthando CMS
                    </a>
                    <p class="navbar-text"><?=$this->pageTitle;?></p>
                </div>

    			<div class="admin-collapse navbar-collapse collapse ">

                    <?php if ($this->identity()):?>
    				<div class="dropdown">
    					<ul class="nav navbar-nav navbar-right">
    						<li><a class="dropdown-toggle" data-toggle="dropdown" href="#"> <i
    								class="glyphicon glyphicon-user"></i> <?=$this->identity()->getFullName();?>
        					        <b class="caret"></b>
    						</a>
                            <?=$this->uthandoNavigation('UthandoUser\Navigation')
                                ->uthandoTbMenu()
                                ->setUlClass('dropdown-menu');?>
    						</li>
    					</ul>
    				</div>
    			<?php endif; ?>
    			</div><!--/.nav-collapse -->
    		</div>
    	</nav>

        <div id="wrapper" class="container-fluid">
            <div class="row-fluid">
                <div class="admin-collapse navbar-collapse collapse">
                    <div id="sidebar-wrapper" class="col-sm-3 col-md-2 sidebar">
                        <?=$this->uthandoNavigation('UthandoAdmin\Navigation')
                            ->uthandoTbMenu()
                            ->setPartial('uthando-admin/partial/side-bar');
                        ;?>
                    </div>
                </div>

                <div id="main-content" class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
                    <div id="alerts" class="row-fluid">
                        <div class="col-md-12">
                            <?=$this->tbFlashMessenger()->render(); ?>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="col-md-12">
                            <?=$this->content; ?>
                            <hr>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="col-md-12">
                            <footer>
                                <p>&copy; 2013 - <?=date('Y'); ?> by <a
                                        href="http://www.shaunfreeman.name">Shaun Freeman</a>. All rights
                                    reserved.
                                </p>
                            </footer>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    	<!-- /container -->
        <?=$this->inlineScript()
            ->appendFile('//cdnjs.cloudflare.com/ajax/libs/metisMenu/2.0.2/metisMenu.min.js')
            ->appendFile($this->basePath('js/uthando-admin.js'))
        ;?>
    </body>
</html>

