<?php $this->bootstrap()->enable(); ?>
<?= $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= $this->headTitle('Control Panel')->setSeparator(' - ')->setAutoEscape(false); ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendName('rating', 'general'); ?>

    <!-- Styles -->
    <?= $this->headLink()
        ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/codemirror/5.11.0/codemirror.css')
        ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/codemirror/5.11.0/addon/hint/show-hint.css')
        ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/codemirror/5.11.0/theme/monokai.css')
        ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.1/summernote.css')
        ->appendStylesheet($this->basePath('css/uthando-admin.css'))
        ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css');
    ?>



    <!-- Scripts -->
    <?= $this->headScript(); ?>

</head>
<body>
<div id="container">
    <header id="header" class="navbar navbar-default navbar-static-top">
        <div class="navbar-header">
            <a type="button" id="button-menu" class="pull-left"><i class="fa fa-indent fa-lg"></i></a>
            <a class="navbar-brand" href="<?= $this->url('home'); ?>">Uthando CMS</a>
        </div>
        <ul class="nav pull-right">
            <li><a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user"></i> <?= $this->identity()->getFullName(); ?>
                    <i class="fa fa-caret-down"></i>
                </a>
                <?= $this->uthandoNavigation('UthandoUser\Navigation')
                    ->uthandoTbMenu()
                    ->setUlClass('dropdown-menu dropdown-menu-right'); ?>
            </li>
        </ul>
    </header>

    <nav id="column-left">
        <?= $this->navigation('UthandoAdmin\Navigation')
            ->menu()
            ->setPartial('uthando-admin/partial/side-bar');; ?>
    </nav>

    <div id="content">
        <div class="page-header">
            <div class="container-fluid">
                <div class="pull-right">
                    <?=$this->placeholder('header-buttons');?>
                </div>
                <h1><?=$this->pageTitle;?></h1>
                <nav class="breadcrumb">
                    <?=$this->navigation('UthandoAdmin\Navigation')
                        ->breadcrumbs()
                        ->setRenderInvisible(true)
                        ->setSeparator(' / ');
                    ?>
                </nav>
            </div>
        </div>

        <div id="alerts" class="container-fluid">
            <?=$this->tbFlashMessenger()->render(); ?>
        </div>

        <div class="container-fluid">
            <?=$this->content; ?>
        </div>
        <hr>
    </div>

    <footer id="footer">
        <p>
            &copy; 2013 - <?=date('Y'); ?> by <a href="http://www.shaunfreeman.name">Shaun Freeman</a>. All rights reserved.
        </p>
    </footer>
</div>

<?= $this->inlineScript()
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/codemirror/5.11.0/codemirror.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/codemirror/5.11.0/addon/hint/show-hint.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/codemirror/5.11.0/addon/hint/xml-hint.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/codemirror/5.11.0/addon/hint/html-hint.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/codemirror/5.11.0/mode/xml/xml.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/codemirror/5.11.0/mode/javascript/javascript.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/codemirror/5.11.0/mode/css/css.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/codemirror/5.11.0/mode/htmlmixed/htmlmixed.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.1/summernote.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js')
    ->appendFile($this->basePath('js/uthando-admin.js')); ?>

<script>
    admin.basePath = '<?=$this->basePath();?>';
</script>

</body>
</html>

