<?php $this->headTitle('Admin Log In') ?>

<?php $this->form->setAttributes([
    'method' => 'post',
    'action' => $this->url('admin/admin', [
        'action' => 'login'
    ]),
]); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <?=$this->translate('Admin Login');?>
            <span class="pull-right">
                <a href="<?=$this->url('admin/admin', [
                    'action' => 'forgot-password'
                ]);?>"><?=$this->translate('Forgot Password');?></a>
            </span>
        </h3>
    </div>
    <div class="panel-body">
        <?=$this->form($this->form);?>
    </div>
</div>