
<?php $routeParams = (is_array($this->routeParams)) ? $this->routeParams : []; ?>
<?php $edit = (is_bool($this->edit)) ? $this->edit : true; ?>
<?php $delete = (is_bool($this->delete)) ? $this->delete : true; ?>
<?php $buttonSize = ($this->buttonSize) ? ' ' . $this->buttonSize : ''; ?>

<?php if ($edit):?>
    <a href="<?=$this->url($this->route, array_merge($routeParams, [
        'action' => 'edit',
    	'id' => $this->id
    ])); ?>" class="btn btn-primary edit-button" data-toggle="tooltip" title="<?=$this->translate('Edit');?>"><i class="fa fa-edit"></i></a>
<?php endif; ?>
&nbsp;
<?php if($delete):?>
<!-- Button to trigger modal -->
<a href="#<?=$this->tableName;?>Model<?=$this->id;?>" class="btn btn-danger btn-tooltip delete-button" title="<?=$this->translate('Delete');?>" data-toggle="modal" data-target="#<?=$this->tableName;?>Model<?=$this->id;?>">
    <i class="fa fa-trash"></i>
</a>
<!-- Modal -->
<div class="modal fade" id="<?=$this->tableName;?>Model<?=$this->id;?>">

    <div class="modal-dialog">
        <div class="modal-content">
        
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 id="<?=$this->tableName;?>Model<?=$this->id;?>Label"><?=$this->translate('Warning');?></h3>
            </div>
            
            <form class="form-horizontal"  method="post" action="<?=$this->url($this->route, array_merge($routeParams, [
                'action' => 'delete',
            ])) ?>">
            <div class="modal-body">
                <p><?=$this->translate('Are you sure you want to delete this');?> <?=$this->tableName;?>.</p>
                <h4 class="text-danger"><?=$this->translate('This action cannot be undone');?></h4>
            </div>
            <input type="hidden" name="<?=$this->pk;?>" value="<?=$this->id;?>">
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">
                    <?=$this->translate("No Don't Do It");?>
                </button>
                <button type="submit" name="submit" class="btn btn-danger" value="delete">
                    <?=$this->translate('Yes Delete It');?>
                </button>
            </div>
            </form>
            
        </div>
    </div>
</div>
<?php endif; ?>