<?php use Zend\Form\Element; ?>

<?php $params = ($this->params) ?: []; ?>

<?php
$select = new Element\Select('count');
$select->setValueOptions(array(
	'25'  => '25',
	'50'  => '50',
	'75'  => '75',
	'100' => '100'
));
$select->setValue((isset($params['count'])) ? $params['count'] : 25 );
$select->setAttribute('class', 'form-control');
?>

<form id="search-<?=$this->name;?>" class="form-inline" method="post">
	<?php foreach($this->searchInputs as $label => $input):?>
	<?php $value = (isset($params[$input])) ? $params[$input] : null; ?>
	<div class="form-group">
	   <?php if ($input instanceof Element): ?>
	       <?=$this->formElement($input->setAttributes([
	           'class' => 'form-control',
	           //'value' => $value
	       ]))?>
	   <?php else: ?>
	       <input type="text" class="form-control" name="<?=$input;?>" placeholder="<?=ucwords($label)?>:" value="">
       <?php endif; ?>
    </div>
    
	<?php endforeach;?>
	<div class="form-group">
    	<?=$this->formSelect($select);?>
	</div>
	<button type="submit" class="btn btn-primary"><i class="icon-search icon-white"></i> Search</button>
	<button type="reset" class="btn btn-default">Reset</button>
</form>
<div class="clearfix">&nbsp;</div>
