
<form id="search-<?=$this->name;?>" class="form-inline" method="post">
	<?php foreach($this->searchInputs as $label => $input):?>
	<div class="form-group">
	   <input type="text" class="form-control" name="<?=$input;?>" placeholder="<?=ucwords($label)?>:">
    </div>
	<?php endforeach;?>
	<div class="form-group">
    	<select name="count" class="form-control">
    		<option selected="selected">25</option>
    		<option>50</option>
    		<option>75</option>
    		<option>100</option>
    	</select>
	</div>
	<button type="submit" class="btn btn-primary"><i class="icon-search icon-white"></i> Search</button>
	<button type="reset" class="btn btn-default">Reset</button>
</form>
<div class="clearfix">&nbsp;</div>
