
<?=$this->headLink();?>
<script>
    var summernoteOptions = {
        height: 300,
        tabsize: 4,
        prettifyHtml:false,
        toolbar: [
            ['style', ['style', 'bold', 'italic', 'strikethrough', 'underline']],
            ['bootstrap', ['bootstrap-helper', 'bootstrap-code', 'bootstrap-inline', 'bootstrap-class-styles']],
            ['edit', ['clear', 'redo', 'undo']],
            ['font', ['fontname', 'fontsize', 'superscript', 'subscript', 'height']],
            ['para', ['ul', 'ol', 'paragraph', 'hr']],
            ['table', ['table']],
            ['insert', ['link', 'video', 'elfinder', 'highlight']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],
        styleTags: ['p', 'blockquote', 'pre', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'],

    };

    if ($('#toggle-summernote').length) {

        if ($('#toggle-summernote').checked === true) {
            $('textarea.editable-textarea').summernote(summernoteOptions);
        }

        $('#toggle-summernote').on('click', function (e) {

            if (this.checked === false) {
                $('textarea.editable-textarea').summernote('destroy');
            } else {
                $('textarea.editable-textarea').summernote(summernoteOptions);
            }

        });

    } else {
        $('textarea.editable-textarea').summernote(summernoteOptions);
    }
</script>

<?php $this->fileManager()->summernote();?>
