
<div class="form-group<?php if ($this->element->getMessages()) echo ' has-error'; ?>">
    <label for="<?=$this->element->getName();?>" class="col-md-<?=$this->options['labelWidth'];?> control-label"><?=$this->element->getLabel();?></label>
    <div class="col-md-<?=$this->options['elementWidth'];?>">
        <?=$this->formElement($this->element->setAttribute('class', 'form-control')); ?>
        <span class="help-block">
            <?php if ($this->element->getOption('inline-help')): ?>
            <?=$this->element->getOption('inline-help');?>
            <?php endif;?>
            <?=$this->formElementErrors($this->element, [
                'class' => 'list-unstyled'
            ]); ?>
        </span>
    </div>
</div>
